creating basic component setup

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -53,49 +53,51 @@ jobs:
         uses: crate-ci/typos@v1.16.25
         with:
           files: |
-            ./docs
+            .
 
-  atmos:
-    name: "Atmos"
-    runs-on:
-      - ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
+  # Add atmos required check once tests are set up
+  # Check the test stack configuration as valid atmos config
+  # atmos:
+  #   name: "Atmos"
+  #   runs-on:
+  #     - ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - name: Setup Node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 16
+  #     - name: Setup Node
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 16
 
-      - name: Install Atmos
-        uses: cloudposse/github-action-setup-atmos@v1
-        with:
-          atmos-version: 1.51.0
+  #     - name: Install Atmos
+  #       uses: cloudposse/github-action-setup-atmos@v1
+  #       with:
+  #         atmos-version: 1.51.0
 
-      # Validate Atmos
-      - name: Atmos Validate
-        id: atmos-validate
-        shell: bash
-        run: |
-          set +e # dont exit on failure yet
-          atmos_validate_stacks="$(atmos validate stacks 2>&1)"
-          atmos_validate_stacks_status="$?"
-          set -e
+  #     # Validate Atmos
+  #     - name: Atmos Validate
+  #       id: atmos-validate
+  #       shell: bash
+  #       run: |
+  #         set +e # dont exit on failure yet
+  #         atmos_validate_stacks="$(atmos validate stacks 2>&1)"
+  #         atmos_validate_stacks_status="$?"
+  #         set -e
 
-          echo "### Atmos Validate Stacks"  >> $GITHUB_STEP_SUMMARY
-          if [[ $atmos_validate_stacks_status -eq 0 ]]; then
-            echo "✅ Valid Atmos stack configuration!" >> $GITHUB_STEP_SUMMARY
-          else
-            echo "❌ Atmos stack validation failed." >> $GITHUB_STEP_SUMMARY
-            echo "\`\`\`console"  >> $GITHUB_STEP_SUMMARY
-            echo "$atmos_validate_stacks"  >> $GITHUB_STEP_SUMMARY
-            echo "\`\`\`"  >> $GITHUB_STEP_SUMMARY
-          fi
+  #         echo "### Atmos Validate Stacks"  >> $GITHUB_STEP_SUMMARY
+  #         if [[ $atmos_validate_stacks_status -eq 0 ]]; then
+  #           echo "✅ Valid Atmos stack configuration!" >> $GITHUB_STEP_SUMMARY
+  #         else
+  #           echo "❌ Atmos stack validation failed." >> $GITHUB_STEP_SUMMARY
+  #           echo "\`\`\`console"  >> $GITHUB_STEP_SUMMARY
+  #           echo "$atmos_validate_stacks"  >> $GITHUB_STEP_SUMMARY
+  #           echo "\`\`\`"  >> $GITHUB_STEP_SUMMARY
+  #         fi
 
-          exit "$atmos_validate_stacks_status" # exit with resulting code
+  #         exit "$atmos_validate_stacks_status" # exit with resulting code
 
   terraform:
-    name: "Terraform"
+    name: "terraform"
     runs-on:
       - ubuntu-latest
     steps:
